
flatpak_remotes:
  flathub:
    state: present
    url: https://flathub.org/repo/flathub.flatpakrepo
  flathub-beta:
    state: present
    url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
  fedora:
    state: present
    url: oci+https://registry.fedoraproject.org

flatpak_flatpaks:
  com.belmoussaoui.Obfuscate:
    state: present
    remote: flathub
  com.bitstower.Markets:
    state: present
    remote: flathub
  com.bitwarden.desktop:
    state: present
    remote: flathub
  com.calibre_ebook.calibre:
    state: absent
    remote: flathub
  com.discordapp.Discord:
    state: present
    remote: flathub
  com.github.gi_lom.dialect:
    state: present
    remote: flathub
  com.github.johnfactotum.Foliate:
    state: present
    remote: flathub
  com.github.junrrein.PDFSlicer:
    state: present
    remote: flathub
  com.github.micahflee.torbrowser-launcher:
    state: present
    remote: flathub
  com.github.ransome1.sleek:
    state: present
    remote: flathub
  com.github.tchx84.Flatseal:
    state: present
    remote: flathub
  com.github.unrud.VideoDownloader:
    state: present
    remote: flathub
  com.google.Chrome:
    state: present
    remote: flathub-beta
  com.jetbrains.IntelliJ-IDEA-Community:
    state: absent
    remote: flathub
  com.spotify.Client:
    state: present
    remote: flathub
  com.valvesoftware.Steam:
    state: present
    remote: flathub
  com.visualstudio.code:
    state: present
    remote: flathub
  com.vscodium.codium:
    state: absent
    remote: flathub
  com.yubico.yubioath:
    state: present
    remote: flathub
  fr.romainvigier.MetadataCleaner:
    state: present
    remote: flathub
  im.riot.Riot:
    state: present
    remote: flathub
  io.github.celluloid_player.Celluloid:
    state: present
    remote: flathub
  org.chromium.Chromium:
    state: present
    remote: flathub
  #org.chromium.Chromium.Codecs:
  #  state: present
  #  remote: flathub
  #org.freedesktop.Platform.ffmpeg-full:
  #  state: present
  #  remote: flathub
  #org.freedesktop.Platform.openh264:
  #  state: present
  #  remote: flathub
  org.gimp.GIMP:
    state: present
    remote: flathub
  org.gnome.Evolution:
    state: present
    remote: flathub
  org.gnome.Extensions:
    state: present
    remote: flathub
  org.gnome.Solanum:
    state: present
    remote: flathub
  #org.gtk.Gtk3theme.Adwaita-dark:
  #  state: present
  #  remote: flathub
  org.mozilla.firefox:
    state: present
    remote: flathub
  org.remmina.Remmina:
    state: absent
    remote: flathub
  org.signal.Signal:
    state: present
    remote: flathub

  org.gnome.baobab:
    state: present
    remote: fedora
  org.gnome.Calculator:
    state: present
    remote: fedora
  org.gnome.Calendar:
    state: present
    remote: fedora
  org.gnome.Characters:
    state: present
    remote: fedora
  org.gnome.clocks:
    state: present
    remote: fedora
  org.gnome.Contacts:
    state: present
    remote: fedora
  org.gnome.Connections:
    state: present
    remote: fedora
  org.gnome.eog:
    state: present
    remote: fedora
  org.gnome.Evince:
    state: present
    remote: fedora
  org.gnome.FileRoller:
    state: present
    remote: fedora
  org.gnome.font-viewer:
    state: present
    remote: fedora
  org.gnome.gedit:
    state: absent
    remote: fedora
  org.gnome.Geary:
    state: present
    remote: fedora
  org.gnome.Logs:
    state: present
    remote: fedora
  org.gnome.Maps:
    state: present
    remote: fedora
  org.fedoraproject.MediaWriter:
    state: absent
    remote: fedora
  org.gnome.Meld:
    state: present
    remote: fedora
  org.gnome.NautilusPreviewer:
    state: present
    remote: fedora
  org.gnome.Screenshot:
    state: present
    remote: fedora
  org.gnome.Weather:
    state: present
    remote: fedora

rpm_ostree_base_packages:
  firefox:
    state: absent
  gnome-software-rpm-ostree:
    state: absent
  gnome-software:
    state: absent

rpm_ostree_kargs:
  'rd.luks.options=discard':
    state: present

rpm_ostree_layered_packages:
  ansible:
    state: present
  atool:
    state: present
  bmon:
    state: present
  checksec:
    state: absent
  compsize:
    state: absent
  docker-compose:
    state: present
  fd-find:
    state: absent
  git:
    state: present
  gnome-shell-extension-appindicator:
    state: present
  gnome-tweaks:
    state: present
  htop:
    state: present
  hyperfine:
    state: absent
  iotop:
    state: present
  microdnf:
    state: present
  moby-engine:
    state: present
  mosh:
    state: absent
  ncdu:
    state: present
  neovim:
    state: present
  net-tools:
    state: present
  nmap:
    state: present
  nmon:
    state: absent
  ranger:
    state: present
  seahorse:
    state: present
  sshfs:
    state: present
  sshuttle:
    state: present
  stow:
    state: present
  strace:
    state: present
  virt-manager:
    state: present
  #libvirt-client:
  #  state: absent
  wl-clipboard:
    state: present
  youtube-dl:
    state: absent
  zsh:
    state: present

etc_firewalld:
  syncthing:
    zone: FedoraWorkstation
    state: enabled

etc_sysctl_params:
  kernel.unprivileged_bpf_disabled:
    value: 1
    state: present
  fs.inotify.max_user_watches:
    value: 524288
    state: present

etc_fstab_entries:
  root:
    path: /
    fstype: btrfs
    opts: noatime,subvol=root,compress=zstd:1,x-systemd.device-timeout=0
    passno: 0
    dump: 0
  home:
    path: /home
    fstype: btrfs
    opts: subvol=home,compress=zstd:1,x-systemd.device-timeout=0
    passno: 0
    dump: 0

users:
  flexo:
    shell: /bin/zsh
